"""Add in room_facilities.facility_id nullable

Revision ID: 84431b455b13
Revises: f3dcbaf4c756
Create Date: 2025-08-27 20:26:02.704527

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "84431b455b13"
down_revision: Union[str, None] = "f3dcbaf4c756"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "room_facilities", "facility_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "room_facilities", "facility_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
