from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "41f6c2ee488d"
down_revision: Union[str, None] = "84431b455b13"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "room_facilities_room_id_fkey", "room_facilities", type_="foreignkey"
    )
    op.drop_constraint(
        "room_facilities_facility_id_fkey", "room_facilities", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "room_facilities", "rooms", ["room_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "room_facilities",
        "facilities",
        ["facility_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "room_facilities", type_="foreignkey")
    op.drop_constraint(None, "room_facilities", type_="foreignkey")
    op.create_foreign_key(
        "room_facilities_facility_id_fkey",
        "room_facilities",
        "facilities",
        ["facility_id"],
        ["id"],
    )
    op.create_foreign_key(
        "room_facilities_room_id_fkey", "room_facilities", "rooms", ["room_id"], ["id"]
    )
